/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jagex3_jagmisc_jagmisc */

#ifndef _Included_jagex3_jagmisc_jagmisc
#define _Included_jagex3_jagmisc_jagmisc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jagex3_jagmisc_jagmisc
 * Method:    nanoTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jagex3_jagmisc_jagmisc_nanoTime
  (JNIEnv *, jclass);

/*
 * Class:     jagex3_jagmisc_jagmisc
 * Method:    Quit0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jagex3_jagmisc_jagmisc_Quit0
  (JNIEnv *, jclass);

/*
 * Class:     jagex3_jagmisc_jagmisc
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jagex3_jagmisc_jagmisc_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
