rootProject.name = "openrs2"

include(
    "all",
    "asm",
    "bundler",
    "cli",
    "compress",
    "compress-cli",
    "conf",
    "crc32",
    "crypto",
    "decompiler",
    "deob",
    "deob-annotations",
    "deob-ast",
    "deob-map",
    "deob-processor",
    "game",
    "nonfree",
    "nonfree:client",
    "nonfree:gl",
    "nonfree:loader",
    "nonfree:signlink",
    "nonfree:unpack",
    "nonfree:unpackclass",
    "util",
    "yaml"
)
