object Versions {
    const val asm = "8.0.1"
    const val bouncyCastlePkix = "1.66"
    const val bouncyCastleProvider = "1.66"
    const val clikt = "2.8.0"
    const val commonsCompress = "1.20"
    const val dependencyLicenseReport = "1.14"
    const val dokka = "0.10.1"
    const val fastutil = "8.4.1"
    const val fernflower = "1.0.4-SNAPSHOT"
    const val guava = "29.0-jre"
    const val guice = "4.2.3"
    const val inlineLogger = "1.0.2"
    const val jackson = "2.11.2"
    const val javaParser = "3.16.1"
    const val jdom = "2.0.6"
    const val jgrapht = "1.5.0"
    const val jimfs = "1.1"
    const val junit = "5.6.2"
    const val kotlin = "1.3.72"
    const val kotlinter = "3.0.2"
    const val logback = "1.2.3"
    const val netty = "4.1.51.Final"
    const val openrs2Natives = "2.0.1"
    const val shadowPlugin = "6.0.0"
    const val versionsPlugin = "0.29.0"
    const val xz = "1.8"
}
