object Versions {
    const val asm = "7.3.1"
    const val bouncyCastle = "1.64"
    const val dependencyLicenseReport = "1.13"
    const val fernflower = "1.0.3"
    const val guava = "28.2-jre"
    const val guice = "4.2.2"
    const val inlineLogger = "1.0.1"
    const val javaParser = "3.15.12"
    const val jimfs = "1.1"
    const val junit = "5.6.0"
    const val kotlin = "1.3.61"
    const val kotlinter = "2.3.0"
    const val logback = "1.2.3"
    const val netty = "4.1.45.Final"
    const val openrs2Natives = "2.0.0"
    const val shadowPlugin = "5.2.0"
    const val versionsPlugin = "0.27.0"
}
