object Versions {
    const val asm = "8.0"
    const val bouncyCastle = "1.64"
    const val clikt = "2.6.0"
    const val commonsCompress = "1.20"
    const val dependencyLicenseReport = "1.13"
    const val fernflower = "1.0.3"
    const val guava = "28.2-jre"
    const val guice = "4.2.3"
    const val inlineLogger = "1.0.2"
    const val javaParser = "3.15.17"
    const val jdom = "2.0.6"
    const val jimfs = "1.1"
    const val junit = "5.6.1"
    const val kotlin = "1.3.71"
    const val kotlinter = "2.3.2"
    const val logback = "1.2.3"
    const val netty = "4.1.48.Final"
    const val openrs2Natives = "2.0.1"
    const val shadowPlugin = "5.2.0"
    const val versionsPlugin = "0.28.0"
}
