/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jaggl_context */

#ifndef _Included_jaggl_context
#define _Included_jaggl_context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jaggl_context
 * Method:    createContext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_context_createContext
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    releaseContext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_context_releaseContext
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_context_destroy
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    swapBuffers
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_context_swapBuffers
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jaggl_context_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    setSwapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jaggl_context_setSwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     jaggl_context
 * Method:    getExtensionsString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jaggl_context_getExtensionsString
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    getAlphaBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jaggl_context_getAlphaBits
  (JNIEnv *, jclass);

/*
 * Class:     jaggl_context
 * Method:    choosePixelFormat1
 * Signature: (Ljava/awt/Component;II)Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_context_choosePixelFormat1
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jaggl_context
 * Method:    makeCurrent1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_context_makeCurrent1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
