/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jaggl_X11_dri */

#ifndef _Included_jaggl_X11_dri
#define _Included_jaggl_X11_dri
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jaggl_X11_dri
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_X11_dri_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jaggl_X11_dri
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jaggl_X11_dri_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
